version: '3'
services:          
    mongodb:
        image: mongo
        networks: 
            - production-network   
    node1:
        build:
            dockerfile: ./docker/node.dockerfile
            context: .
        command: nodemon server.js
        volumes:
            - .:/app
        image: douglasq/alura-books
        container_name: linkapi-1
        ports:
            - "3000:3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"
networks: 
    production-network:
        driver: bridge